### ISSUE TITLE
Cannot make it work with custom sidebar

### ISSUE THREAD

**Issue by anelad** [bikecoders/ngx-sticky#17]
I have content and sidebar, created using FlexLayout. The content width is 70, and the sidebar width is 30. Since the content is longer than the sidebar, I want to make it sticky when I scroll down but couldn't make it work. Below, I shared a simple Stackblitz project. Any help pls? Thank you. 

[stackblitz](https://stackblitz.com/edit/angular-sticky-siddebar)

**Comment by dianjuar** [comment]
It's because the height of the element you want to set sticky

[Solution](https://stackblitz.com/edit/angular-sticky-siddebar-pi917z?file=src/app/app.component.html)

**Comment by anelad** [comment]
Thank you @dianjuar. But why? Why should I set a pre-defined dummy height?

**Comment by dianjuar** [comment]
It's a css problem.

The element that you want to set sticky right now, its height covers all the screen so it never scroll down it just have the right size. If you set that dummy hight he is not covering all the height.

Look at this gif
![ezgif-4-d4725dca7d4d](https://user-images.githubusercontent.com/7026066/67413412-b4d82e00-f586-11e9-97fa-817cb426c4eb.gif)


You will face this kind of problems working with sticky property, you can use `background-color: red;` to see what is happening, that will help you to see graphically what is going on

**Comment by dianjuar** [comment]
I saw that you want that background in yellow when it's in sticky mode and is not working... I will take a look why is that happening.

**Comment by anelad** [comment]
> I saw that you want that background in yellow when it's in sticky mode and is not working... I will take a look why is that happening.

It's not a big deal for me, I will not use the extra class. But I have another problem right now. I've updated my code, could you check it?

**Comment by anelad** [comment]
Ok, I handled the second problem. You do not need to check the code. But I need that extra class I suppose; to add top margin when the item is sticky

**Comment by dianjuar** [comment]
For your problem about the top margin, you can see the property `top` that was designed for that

https://github.com/bikecoders/ngx-sticky/blob/master/README.md#properties

**Comment by anelad** [comment]
Oh, I missed that. Thanks for your time.

**Comment by dianjuar** [comment]
But your custom class is not being applied that is very weird, I try to make it work like 30 min without success, I will try it again at night.

**Comment by dianjuar** [comment]
A recommendation that I can give you is do not use this directive if you only need to set a sticky element, you can add that by just using css, not javascript needed at all to accomplish that. 

But if you need to **set an css class when certain element is being sticky**, this is the right tool for you

**Comment by dianjuar** [comment]
Please keep this issue open to see what is going on

**Comment by anelad** [comment]
I'm done with it @dianjuar. Thank you for your help!
